// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using advans_backend.Data;

#nullable disable

namespace advans_backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240404170426_InitialUserDat")]
    partial class InitialUserDat
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("advans_backend.Models.Client", b =>
                {
                    b.Property<int>("Id_Client")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Client"));

                    b.Property<string>("Acitivite")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Age")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Agence")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Cycle")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date_dernier_visite")
                        .HasColumnType("datetime2");

                    b.Property<string>("Interlocuteur_principal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Nombre_enfants")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rais_soc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Secteur_act")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Segment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sigle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sit_fam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sit_imm")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sous_Activite")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeCompte")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Client");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("advans_backend.Models.Demande_credit", b =>
                {
                    b.Property<int>("Id_Demande")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Demande"));

                    b.Property<string>("Canal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Capacite")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescriptionObjet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Disponibilite")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DureeDemandee")
                        .HasColumnType("int");

                    b.Property<int>("Id_Client")
                        .HasColumnType("int");

                    b.Property<string>("Montant")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NbrCredit_EnCours")
                        .HasColumnType("int");

                    b.Property<string>("NomGestionnaire")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Produit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypeObjet")
                        .HasColumnType("int");

                    b.Property<string>("commentaire")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("institutions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("num_version")
                        .HasColumnType("int");

                    b.HasKey("Id_Demande");

                    b.HasIndex("Id_Client");

                    b.ToTable("Demande_credit");
                });

            modelBuilder.Entity("advans_backend.Models.Demande_credit+Appro", b =>
                {
                    b.Property<int>("Id_Appro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Appro"));

                    b.Property<int?>("Demande_creditId_Demande")
                        .HasColumnType("int");

                    b.Property<int>("Frequence")
                        .HasColumnType("int");

                    b.Property<long>("MontantMoyen_FCFA")
                        .HasColumnType("bigint");

                    b.HasKey("Id_Appro");

                    b.HasIndex("Demande_creditId_Demande");

                    b.ToTable("Appro");
                });

            modelBuilder.Entity("advans_backend.Models.Demande_credit+Garant", b =>
                {
                    b.Property<int>("idGarant")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idGarant"));

                    b.Property<int?>("Demande_creditId_Demande")
                        .HasColumnType("int");

                    b.Property<string>("NomGarant")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RelationClient")
                        .HasColumnType("int");

                    b.HasKey("idGarant");

                    b.HasIndex("Demande_creditId_Demande");

                    b.ToTable("Garant");
                });

            modelBuilder.Entity("advans_backend.Models.Demande_credit+Garantie", b =>
                {
                    b.Property<int>("idGarantie")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idGarantie"));

                    b.Property<int?>("Demande_creditId_Demande")
                        .HasColumnType("int");

                    b.Property<string>("Proprietaire")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Valeur_estime")
                        .HasColumnType("bigint");

                    b.HasKey("idGarantie");

                    b.HasIndex("Demande_creditId_Demande");

                    b.ToTable("Garantie");
                });

            modelBuilder.Entity("advans_backend.Models.Demande_credit+Vente", b =>
                {
                    b.Property<int>("idvente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idvente"));

                    b.Property<int?>("Demande_creditId_Demande")
                        .HasColumnType("int");

                    b.Property<int>("Frequence")
                        .HasColumnType("int");

                    b.Property<long>("ValeurBasse")
                        .HasColumnType("bigint");

                    b.Property<long>("ValeurHaute")
                        .HasColumnType("bigint");

                    b.Property<long>("ValeurMoyenne")
                        .HasColumnType("bigint");

                    b.HasKey("idvente");

                    b.HasIndex("Demande_creditId_Demande");

                    b.ToTable("Vente");
                });

            modelBuilder.Entity("advans_backend.Models.user", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("advans_backend.Models.Demande_credit", b =>
                {
                    b.HasOne("advans_backend.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("Id_Client")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("advans_backend.Models.Demande_credit+Appro", b =>
                {
                    b.HasOne("advans_backend.Models.Demande_credit", null)
                        .WithMany("Appros")
                        .HasForeignKey("Demande_creditId_Demande");
                });

            modelBuilder.Entity("advans_backend.Models.Demande_credit+Garant", b =>
                {
                    b.HasOne("advans_backend.Models.Demande_credit", null)
                        .WithMany("Garants")
                        .HasForeignKey("Demande_creditId_Demande");
                });

            modelBuilder.Entity("advans_backend.Models.Demande_credit+Garantie", b =>
                {
                    b.HasOne("advans_backend.Models.Demande_credit", null)
                        .WithMany("Garanties")
                        .HasForeignKey("Demande_creditId_Demande");
                });

            modelBuilder.Entity("advans_backend.Models.Demande_credit+Vente", b =>
                {
                    b.HasOne("advans_backend.Models.Demande_credit", null)
                        .WithMany("Ventes")
                        .HasForeignKey("Demande_creditId_Demande");
                });

            modelBuilder.Entity("advans_backend.Models.Demande_credit", b =>
                {
                    b.Navigation("Appros");

                    b.Navigation("Garanties");

                    b.Navigation("Garants");

                    b.Navigation("Ventes");
                });
#pragma warning restore 612, 618
        }
    }
}
